### ISSUE TITLE
How to write the BVHViewer.exe

### ISSUE THREAD

**Issue by Vincy-Ying** [oneThousand1000/3DPointsMotionVisualization#1]
Hello, I want to kow the source code of the BVHViewer.exe, can you send it to me? Thanks!

**Comment by oneThousand1000** [comment]
Sorry, we downloaded the application from the Internet and forgot explaining it in the readme, we already have updated more information in the readme, and you can find another version of the source code of BVHviewer at https://github.com/mrzli/bvhviewer, which is similar to the BVHViewer.exe in our project.

Hope this helps you!:)



-----原始邮件-----
发件人:Vincy-Ying <notifications@github.com>
发送时间:2020-10-02 22:14:15 (星期五)
收件人: oneThousand1000/3DPointsMotionVisualization <3DPointsMotionVisualization@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [oneThousand1000/3DPointsMotionVisualization] How to write the BVHViewer.exe (#1)






Hello, I want to kow the source code of the BVHViewer.exe, can you send it to me? Thanks!

**Comment by Vincy-Ying** [comment]
> Sorry, we downloaded the application from the Internet and forgot explaining it in the readme, we already have updated more information in the readme, and you can find another version of the source code of BVHviewer at https://github.com/mrzli/bvhviewer, which is similar to the BVHViewer.exe in our project.
> 
> Hope this helps you!:)
> …

Okay, Thanks!
